sudo: required
language: bash
services:
  - docker
before_install:
  - docker pull jmiahman/rpmbuilder
env:
  - MOCK_CONFIG="mageia-6-i386"
  - MOCK_CONFIG="mageia-6-x86_64"
script:
  - docker run -e MOCK_CONFIG="${MOCK_CONFIG}" -v "$(pwd):/rpmbuild" --privileged=true jmiahman/rpmbuilder

after_success:
  - pip install copr-cli simplejson
  - openssl aes-256-cbc -K $<ENCRYPTED KEY VAR> -iv $<ENCRYPTED KEY VAR> -in .copr.enc -out .copr -d
  - if [ ! -z "${TRAVIS_TAG}" ]; then copr-cli --config .copr build -r Mageia-6-x86_64 jmiahman/mklivecd /rpmbuild/*.src.rpm; fi
