sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=mageia
    - COPR_REPOSITORY=jmiahman/mklivecd
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=mageia OS_DIST=mageia OS_VERSION=6

services:
  - docker

before_install:
- docker pull mageia:latest

install: true

script:

- docker run -it -v /var/run/docker.sock:/var/run/docker.sock mageia:latest sh -c "dnf update ; dnf install rpm-build -y ; bash"

#  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}

after_success:
  - pip install copr-cli simplejson
  - openssl aes-256-cbc -K $<ENCRYPTED KEY VAR> -iv $<ENCRYPTED KEY VAR> -in .copr.enc -out .copr -d
  - if [ ! -z "${TRAVIS_TAG}" ]; then copr-cli --config .copr build -r ${OS_DIST}-${OS_VERSION}-${OS_ARCH} ${COPR_REPOSITORY} *.src.rpm; fi
