sudo: required
language: bash
services:
  - docker

install: true
  
before_install:
  - docker pull jmiahman/mageia-rpmbuilder
  
script:
  - export DID=$(docker image ls | grep -m1 mageia-rpmbuilder | awk '{print $3}')
  - echo $DID
  - docker run -d -v "$(pwd):/rpmbuild" -v "/dev:/dev" $DID tail -f /dev/null
  - export CID=$(docker ps -l | awk '{print $1}' | grep -v -m1 'CONTAINER')
  - echo $CID
  - docker exec $CID /bin/sh -c 'cd /rpmbuild && make spec && make srpm && make rpm' --privileged=true
  - docker exec $CID /bin/sh -c 'dnf install /rpmbuild/RPMS/*/*.rpm -y' --privileged=true
  - docker exec $CID /bin/sh -c 'mklivecd --tmp /rpmbuild/mklivecd --gzip /rpmbuild/live.iso' --privileged=true
  - file /rpmbuild/live.iso

after_success:
  - sudo -H pip install --upgrade pyOpenSSL ndg-httpsclient pyasn1 requests[security] marshmallow copr-cli simplejson
  - openssl aes-256-cbc -K $encrypted_35dd8c7ad7ad_key -iv $encrypted_35dd8c7ad7ad_iv -in .copr.enc -out .copr -d
  - if [ -f ./SRPMS/*.src.rpm ]; then copr-cli --config .copr build -r Mageia-6-x86_64 jmiahman/mklivecd ./SRPMS/*.src.rpm & copr-cli --config .copr build -r Mageia-6-x86_64 jmiahman/Unity-Linux ./SRPMS/*.src.rpm; fi 
