sudo: required
language: bash
services:
  - docker

install: true
  
before_install:
  - docker pull jmiahman/mageia-rpmbuilder
env:
  - MOCK_CONFIG="mageia-6-i386"
  - MOCK_CONFIG="mageia-6-x86_64"
  
script:
  - export DID=$(docker image ls | grep -m1 mageia-rpmbuilder | awk '{print $3}')
  - echo $DID
  - docker run -d -v "$(pwd):/rpmbuild" $DID tail -f /dev/null
  - export CID=$(docker ps -l | awk '{print $1}' | grep -v -m1 'CONTAINER')
  - echo $CID
  - docker exec $CID /bin/sh -c 'dnf install intltool -y && cd /rpmbuild && make srpm' --privileged=true

after_success:
  - apt-get upgrade -y
  - pip install marshmallow copr-cli simplejson
  - openssl aes-256-cbc -K $<ENCRYPTED KEY VAR> -iv $<ENCRYPTED KEY VAR> -in .copr.enc -out .copr -d
  - if [ ! -z "${TRAVIS_TAG}" ]; then copr-cli --config .copr build -r Mageia-6-x86_64 jmiahman/mklivecd /rpmbuild/SRPMS/*.src.rpm; fi
