sudo: required
language: bash
services:
  - docker
install: true

before_install:
  - openssl aes-256-cbc -K $encrypted_2312699044a7_key -iv $encrypted_2312699044a7_iv -in .stuff.tar.gz.enc -out stuff.tar.gz -d
  - file stuff.tar.gz
  - tar xzvf stuff.tar.gz -C /tmp/
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/stuff/.deploy
  - ssh-add /tmp/stuff/.deploy
  - mv /tmp/stuff/.host ~/.ssh/config
  - docker pull jmiahman/mageia-rpmbuilder

script:
  - export DID=$(docker image ls | grep -m1 mageia-rpmbuilder | awk '{print $3}')
  - echo $DID
  - docker run --hostname=unity-linux --privileged=true -d -v "$(pwd):/rpmbuild" -v "/dev:/dev" $DID tail -f /dev/null
  - export CID=$(docker ps -l | awk '{print $1}' | grep -v -m1 'CONTAINER')
  - echo $CID
  - docker exec $CID /bin/sh -c 'cd /rpmbuild && make spec && make srpm && make rpm &>> /rpmbuild/iso_build.log' --privileged=true
  - docker exec $CID /bin/sh -c 'dnf install /rpmbuild/RPMS/*/*.rpm task-unity-lxqt -y &>> /rpmbuild/iso_build.log' --privileged=true
  - mkdir build_iso  
  - docker exec -d $CID /bin/sh -c 'mklivecd --tmp /rpmbuild --xz /rpmbuild/live.iso &>> /rpmbuild/iso_build.log'
  - docker exec $CID /bin/sh -c 'while ps ax | grep mklivecd | grep -v grep > /dev/null ; do sleep 60 ; export x="$(($x+1))" ; echo "--==|mklivecd has been running for $x minute(s)|==--" ; done'
  - export LIVE_ISO=$(readlink -f ./*.iso)
  - mv $LIVE_ISO ./build_iso/
  - mv iso_build.log ./build_iso/
  - rsync -arz --progress --rsh=ssh -e "ssh -o StrictHostKeyChecking=no" ./build_iso foobar2:public_html/pub/isos/
  - rsync -arz --progress --rsh=ssh -e "ssh -o StrictHostKeyChecking=no" ./build_iso foobar:/var/www/html/isos/
  - if [ -z $LIVE_ISO ]; then echo "ISO Creation Failed"; exit 1;fi

after_success:
  - sudo -H pip install --upgrade pyOpenSSL ndg-httpsclient pyasn1 requests[security] marshmallow copr-cli simplejson
  - if [ -f ./SRPMS/*.src.rpm ]; then copr-cli --config /tmp/stuff/.copr build -r Mageia-6-x86_64 jmiahman/mklivecd ./SRPMS/*.src.rpm & copr-cli --config /tmp/stuff/.copr build -r Mageia-6-x86_64 jmiahman/Unity-Linux ./SRPMS/*.src.rpm; fi
